version: 2.1
orbs:
  win: circleci/windows@2.4.0
jobs:
  percy-finalize:
    docker:
      - image: percyio/agent
    steps:
      - run: percy finalize --all

  artifacts:
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
        environment:
          PYVERSION: python37
    steps:
      - checkout
      - run: echo $PYVERSION > ver.txt
      - restore_cache:
          key: dep-{{ checksum ".circleci/config.yml" }}-{{ checksum "ver.txt" }}-{{ checksum "requires-dev.txt" }}-{{ checksum "requires-install.txt" }}-{{ checksum "requires-testing.txt" }}
      - attach_workspace:
          at: ~/dash
      - store_artifacts:
          path: ~/dash/packages
          destination: /tmp/packages

  lint-unit-37: &lint-unit
    working_directory: ~/dash
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
        environment:
          PYVERSION: python37

    steps:
      - checkout
      - run: echo $PYVERSION > ver.txt
      - restore_cache:
          key: dep-{{ checksum ".circleci/config.yml" }}-{{ checksum "ver.txt" }}-{{ checksum "requires-dev.txt" }}-{{ checksum "requires-install.txt" }}-{{ checksum "requires-testing.txt" }}
      - run:
          name: ️️🏗️ pip dev requirements
          command: |
            sudo pip install --upgrade virtualenv --progress-bar off
            python -m venv venv || virtualenv venv && . venv/bin/activate
            pip install -e . --no-cache-dir -r requires-install.txt -r requires-dev.txt -r requires-testing.txt --progress-bar off
      - save_cache:
          key: dep-{{ checksum ".circleci/config.yml" }}-{{ checksum "ver.txt" }}-{{ checksum "requires-dev.txt" }}-{{ checksum "requires-install.txt" }}-{{ checksum "requires-testing.txt" }}
          paths:
              - venv
      - run:
          name: 🌸 Python & JS Lint
          command: |
            . venv/bin/activate
            set -eo pipefail
            pip install -e . --progress-bar off && pip list | grep dash
            npm install --production && npm run initialize
            npm run lint
      - run:
          name: 🐍 Python Unit Tests & ☕ JS Unit Tests
          command: |
            . venv/bin/activate
            npm run test.unit

  lint-unit-36:
      <<: *lint-unit
      docker:
        - image: circleci/python:3.6-stretch-node-browsers
          environment:
            PYLINTRC: .pylintrc
            PYVERSION: python36

  lint-unit-27:
      <<: *lint-unit
      docker:
        - image: circleci/python:2.7-stretch-node-browsers
          environment:
            PYLINTRC: .pylintrc
            PYVERSION: python27

  build-core-37: &build-core
    working_directory: ~/dash
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
        environment:
          PYLINTRC: .pylintrc37
          PYVERSION: python37
    steps:
      - checkout
      - run: echo $PYVERSION > ver.txt
      - restore_cache:
          key: dep-{{ checksum ".circleci/config.yml" }}-{{ checksum "ver.txt" }}-{{ checksum "requires-dev.txt" }}-{{ checksum "requires-install.txt" }}-{{ checksum "requires-testing.txt" }}
      - run:
          name: ️️🏗️ pip dev requirements
          command: |
            sudo pip install --upgrade virtualenv
            python -m venv venv || virtualenv venv && . venv/bin/activate
            sed -i '/dash-/d' requires-install.txt
            pip install -e . --no-cache-dir -r requires-install.txt -r requires-dev.txt -r requires-testing.txt --progress-bar off
      - save_cache:
          key: dep-{{ checksum ".circleci/config.yml" }}-{{ checksum "ver.txt" }}-{{ checksum "requires-dev.txt" }}-{{ checksum "requires-install.txt" }}-{{ checksum "requires-testing.txt" }}
          paths:
              - venv
      - run:
          name: ️️🏗️ build core
          command: |
              . venv/bin/activate && pip install --no-cache-dir --upgrade -e . --progress-bar off && mkdir packages
              cd dash-renderer && renderer build && python setup.py sdist && mv dist/* ../packages/ && cd ..
              git clone --depth 1 https://github.com/plotly/dash-core-components.git
              cd dash-core-components && npm ci && npm run build && python setup.py sdist && mv dist/* ../packages/  && cd ..
              git clone --depth 1 https://github.com/plotly/dash-renderer-test-components
              cd dash-renderer-test-components && npm ci && npm run build:all && python setup.py sdist && mv dist/* ../packages/ && cd ..
              ls -la packages
      - persist_to_workspace:
          root: ~/dash
          paths:
            - packages/*.tar.gz

  build-core-36:
      <<: *build-core
      docker:
        - image: circleci/python:3.6-stretch-node-browsers
          environment:
            PYVERSION: python36

  build-core-27:
      <<: *build-core
      docker:
        - image: circleci/python:2.7-stretch-node-browsers
          environment:
            PYVERSION: python27

  build-misc-37: &build-misc
    working_directory: ~/dash
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
        environment:
          PYVERSION: python37

    steps:
      - checkout
      - run: echo $PYVERSION > ver.txt
      - restore_cache:
          key: dep-{{ checksum ".circleci/config.yml" }}-{{ checksum "ver.txt" }}-{{ checksum "requires-dev.txt" }}-{{ checksum "requires-install.txt" }}-{{ checksum "requires-testing.txt" }}
      - run:
          name: ️️🏗️ pip dev requirements
          command: |
            sudo pip install --upgrade virtualenv --quiet
            python -m venv venv || virtualenv venv && . venv/bin/activate
            pip install -e . --no-cache-dir -r requires-install.txt -r requires-dev.txt -r requires-testing.txt --progress-bar off
      - save_cache:
          key: dep-{{ checksum ".circleci/config.yml" }}-{{ checksum "ver.txt" }}-{{ checksum "requires-dev.txt" }}-{{ checksum "requires-install.txt" }}-{{ checksum "requires-testing.txt" }}
          paths:
              - venv
      - run:
          name: ️️🏗️ build misc
          command: |
              . venv/bin/activate && pip install --no-cache-dir --upgrade -e . --progress-bar off && mkdir packages
              git clone --depth 1 https://github.com/plotly/dash-table.git
              cd dash-table && npm ci && npm run build && python setup.py sdist && mv dist/* ../packages/ && cd ..
              git clone --depth 1 https://github.com/plotly/dash-html-components.git
              cd dash-html-components && npm ci && npm run build && python setup.py sdist && mv dist/* ../packages/ && cd ..
              ls -la packages
      - persist_to_workspace:
          root: ~/dash
          paths:
            - packages/*.tar.gz

  build-misc-36:
      <<: *build-misc
      docker:
        - image: circleci/python:3.6-stretch-node-browsers
          environment:
            PYVERSION: python36

  build-misc-27:
      <<: *build-misc
      docker:
        - image: circleci/python:2.7-stretch-node-browsers
          environment:
            PYVERSION: python27

  build-windows-37: &build-windows
    working_directory: ~/dash
    executor:
      name: win/default
      shell: bash.exe
    environment:
      PYVERSION: python37
    steps:
      - checkout
      - run: echo $PYVERSION > ver.txt
      - restore_cache:
          key: dep-{{ checksum ".circleci/config.yml" }}-{{ checksum "ver.txt" }}-{{ checksum "requires-dev.txt" }}-{{ checksum "requires-install.txt" }}-{{ checksum "requires-testing.txt" }}
      - run:
          name: ️️🏗️ pip dev requirements
          command: |
            pip install --upgrade virtualenv
            virtualenv venv
            source venv/Scripts/activate
            sed -i '/dash-/d' requires-install.txt
            pip install -e . --no-cache-dir -r requires-install.txt -r requires-dev.txt -r requires-testing.txt --progress-bar off
      - save_cache:
          key: dep-{{ checksum ".circleci/config.yml" }}-{{ checksum "ver.txt" }}-{{ checksum "requires-dev.txt" }}-{{ checksum "requires-install.txt" }}-{{ checksum "requires-testing.txt" }}
          paths:
              - venv
      - run:
          name: ️️🏗️ build core
          command: |
              source venv/Scripts/activate && pip install --no-cache-dir --upgrade -e . --progress-bar off && mkdir packages
              cd dash-renderer && renderer build && python setup.py sdist && mv dist/* ../packages/ && cd ..
              git clone --depth 1 https://github.com/plotly/dash-core-components.git
              cd dash-core-components && npm ci && npm run build && python setup.py sdist && mv dist/* ../packages/  && cd ..
              git clone --depth 1 https://github.com/plotly/dash-renderer-test-components
              cd dash-renderer-test-components && npm ci && npm run build:all && python setup.py sdist && mv dist/* ../packages/ && cd ..
              ls -la packages
      - persist_to_workspace:
          root: ~/dash
          paths:
            - packages/*.tar.gz

  test-37: &test
    working_directory: ~/dash
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
        environment:
          PERCY_PARALLEL_TOTAL: -1
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: True
          PYVERSION: python37
    parallelism: 3
    steps:
      - checkout
      - run: echo $PYVERSION > ver.txt
      - restore_cache:
          key: dep-{{ checksum ".circleci/config.yml" }}-{{ checksum "ver.txt" }}-{{ checksum "requires-dev.txt" }}-{{ checksum "requires-install.txt" }}-{{ checksum "requires-testing.txt" }}
      - attach_workspace:
          at: ~/dash
      - run:
          name: ️️🏗️  Install packages
          command: |
            . venv/bin/activate
            npm install --production
            cd packages && ls -la
            find . -name "*.gz" | xargs pip install --no-cache-dir --ignore-installed && cd ..
            sed -i '/dash/d' requires-install.txt
            pip install --no-cache-dir --ignore-installed .
            pip list | grep dash
      - run:
          name: 🧪 Run Integration Tests
          command: |
            . venv/bin/activate
            npm run test.integration
      - store_artifacts:
          path: test-reports
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: /tmp/dash_artifacts
      - run:
          name: 🦔 percy finalize
          command: npx percy finalize --all
          when: on_fail

  test-36:
      <<: *test
      docker:
        - image: circleci/python:3.6-stretch-node-browsers
          environment:
            PERCY_ENABLE: 0
            PYVERSION: python36

  test-27:
      <<: *test
      docker:
        - image: circleci/python:2.7-stretch-node-browsers
          environment:
            PERCY_ENABLE: 0
            PYVERSION: python27

workflows:
  version: 2
  python3.7:
    jobs:
      - lint-unit-37
      - build-core-37
      - build-windows-37
      - build-misc-37
      - test-37:
          requires:
            - build-core-37
            - build-misc-37
      - percy-finalize:
          requires:
            - test-37
      - artifacts:
          requires:
            - percy-finalize
          filters:
            branches:
              only:
                - master
                - dev
            tags:
              only: /v*/

  python3.6:
    jobs:
      - lint-unit-36
      - build-core-36
      - build-misc-36
      - test-36:
          requires:
            - build-core-36
            - build-misc-36
  python2.7:
    jobs:
      - lint-unit-27
      - build-core-27
      - build-misc-27
      - test-27:
          requires:
            - build-core-27
            - build-misc-27
